import a from './sound_files/a.ogg'
import æ from './sound_files/æ.ogg'
import ɐ from './sound_files/ɐ.ogg'
import ɑ from './sound_files/ɑ.ogg'
import ɒ from './sound_files/ɒ.ogg'
import b from './sound_files/b.ogg'
import ʙ from './sound_files/ʙ.ogg'
import ɓ from './sound_files/ɓ.ogg'
import c from './sound_files/c.ogg'
import ç from './sound_files/ç.ogg'
import d from './sound_files/d.ogg'
import ð from './sound_files/ð.ogg'
import dʒ from './sound_files/dʒ.ogg'
import ɖ from './sound_files/ɖ.oga'
import ɗ from './sound_files/ɗ.ogg'
import e from './sound_files/e.ogg'
import ə from './sound_files/ə.ogg'
import ɛ from './sound_files/ɛ.ogg'
import ɘ from './sound_files/ɘ.ogg'
import ɜ from './sound_files/ɜ.ogg'
import ɞ from './sound_files/ɞ.ogg'
import ɤ from './sound_files/ɤ.ogg'
import f from './sound_files/f.ogg'
import g from './sound_files/g.ogg'
import ɢ from './sound_files/ɢ.oga'
import ɠ from './sound_files/ɠ.ogg'
import ɣ from './sound_files/ɣ.ogg'
import h from './sound_files/h.ogg'
import ħ from './sound_files/ħ.ogg'
import ɦ from './sound_files/ɦ.ogg'
import i from './sound_files/i.ogg'
import ɪ from './sound_files/ɪ.ogg'
import ɨ from './sound_files/ɨ.ogg'
import j from './sound_files/j.ogg'
import ʝ from './sound_files/ʝ.ogg'
import ɟ from './sound_files/ɟ.ogg'
import k from './sound_files/k.ogg'
import kʼ from './sound_files/kʼ.ogg'
import l from './sound_files/l.ogg'
import ʟ from './sound_files/ʟ.ogg'
import ɬ from './sound_files/ɬ.ogg'
import ɭ from './sound_files/ɭ.ogg'
import ɮ from './sound_files/ɮ.ogg'
import ʎ from './sound_files/ʎ.ogg'
import m from './sound_files/m.ogg'
import ɱ from './sound_files/ɱ.ogg'
import n from './sound_files/n.ogg'
import ɴ from './sound_files/ɴ.ogg'
import ɲ from './sound_files/ɲ.ogg'
import ɳ from './sound_files/ɳ.ogg'
import ŋ from './sound_files/ŋ.ogg'
import o from './sound_files/o.ogg'
import ø from './sound_files/ø.ogg'
import œ from './sound_files/œ.ogg'
import ɶ from './sound_files/ɶ.ogg'
import ɔ from './sound_files/ɔ.ogg'
import ɵ from './sound_files/ɵ.ogg'
import p from './sound_files/p.ogg'
import pʼ from './sound_files/pʼ.ogg'
import ɸ from './sound_files/ɸ.ogg'
import q from './sound_files/q.ogg'
import r from './sound_files/r.ogg'
import ʀ from './sound_files/ʀ.ogg'
import ɹ from './sound_files/ɹ.ogg'
import ɻ from './sound_files/ɻ.ogg'
import ɽ from './sound_files/ɽ.ogg'
import ɾ from './sound_files/ɾ.ogg'
import ʁ from './sound_files/ʁ.ogg'
import s from './sound_files/s.ogg'
import ʂ from './sound_files/ʂ.ogg'
import ʃ from './sound_files/ʃ.ogg'
import t from './sound_files/t.ogg'
import tʃ from './sound_files/tʃ.ogg'
import tʼ from './sound_files/tʼ.ogg'
import ʈ from './sound_files/ʈ.oga'
import u from './sound_files/u.ogg'
import ʉ from './sound_files/ʉ.ogg'
import ɯ from './sound_files/ɯ.ogg'
import ɰ from './sound_files/ɰ.ogg'
import ʊ from './sound_files/ʊ.ogg'
import v from './sound_files/v.ogg'
import ʋ from './sound_files/ʋ.ogg'
import ⱱ from './sound_files/ⱱ.ogg'
import ʌ from './sound_files/ʌ.ogg'
import w from './sound_files/w.ogg'
import x from './sound_files/x.ogg'
import y from './sound_files/y.ogg'
import ʏ from './sound_files/ʏ.ogg'
import z from './sound_files/z.ogg'
import ʐ from './sound_files/ʐ.ogg'
import ʒ from './sound_files/ʒ.ogg'
import ʔ from './sound_files/ʔ.ogg'
import ʕ from './sound_files/ʕ.ogg'
import ǀ from './sound_files/ǀ.ogg'
import ǁ from './sound_files/ǁ.ogg'
import ǂ from './sound_files/ǂ.ogg'
import ǃ from './sound_files/ǃ.ogg'
import ʘ from './sound_files/ʘ.ogg'
import β from './sound_files/β.ogg'
import θ from './sound_files/θ.ogg'
import χ from './sound_files/χ.ogg'

const sound = {
'a' : a ,
'æ' : æ ,
'ɐ' : ɐ ,
'ɑ' : ɑ ,
'ɒ' : ɒ ,
'b' : b ,
'ʙ' : ʙ ,
'ɓ' : ɓ ,
'c' : c ,
'ç' : ç ,  
'd' : d ,
'ð' : ð ,
'dʒ' : dʒ,
'ɖ' : ɖ ,
'ɗ' : ɗ ,
'e' : e ,
'ə' : ə ,
'ɛ' : ɛ ,
'ɘ' : ɘ ,
'ɜ' : ɜ ,
'ɞ' : ɞ ,
'ɤ' : ɤ ,
'f' : f ,
'g' : g ,
'ɢ' : ɢ ,
'ɠ' : ɠ ,
'ɣ' : ɣ ,
'h' : h ,
'ħ' : ħ ,
'ɦ' : ɦ ,
'i' : i ,
'ɪ' : ɪ ,
'ɨ' : ɨ ,
'j' : j ,
'ʝ' : ʝ ,
'ɟ' : ɟ ,
'k' : k ,
'kʼ' : kʼ,
'l' : l ,
'ʟ' : ʟ ,
'ɬ' : ɬ ,
'ɭ' : ɭ ,
'ɮ' : ɮ ,
'ʎ' : ʎ ,
'm' : m ,
'ɱ' : ɱ ,
'n' : n ,
'ɴ' : ɴ ,
'ɲ' : ɲ ,
'ɳ' : ɳ ,
'ŋ' : ŋ ,
'o' : o ,
'ø' : ø ,
'œ' : œ ,
'ɶ' : ɶ ,
'ɔ' : ɔ ,
'ɵ' : ɵ ,
'p' : p ,
'pʼ' : pʼ,
'ɸ' : ɸ ,
'q' : q ,
'r' : r ,
'ʀ' : ʀ ,
'ɹ' : ɹ ,
'ɻ' : ɻ ,
'ɽ' : ɽ ,
'ɾ' : ɾ ,
'ʁ' : ʁ ,
's' : s ,
'ʂ' : ʂ ,
'ʃ' : ʃ ,
't' : t ,
'tʃ' : tʃ,
'tʼ' : tʼ,
'ʈ' : ʈ ,
'u' : u ,
'ʉ' : ʉ ,
'ɯ' : ɯ ,
'ɰ' : ɰ ,
'ʊ' : ʊ ,
'v' : v ,
'ʋ' : ʋ ,
'ⱱ' : ⱱ ,
'ʌ' : ʌ ,
'w' : w ,
'x' : x ,
'y' : y ,
'ʏ' : ʏ ,
'z' : z ,
'ʐ' : ʐ ,
'ʒ' : ʒ ,
'ʔ' : ʔ ,
'ʕ' : ʕ ,
'ǀ' : ǀ ,
'ǁ' : ǁ ,
'ǂ' : ǂ ,
'ǃ' : ǃ ,
'ʘ' : ʘ ,
'β' : β ,
'θ' : θ ,
'χ' : χ ,
}
export {sound}