import a from '../sounds/a.ogg'
import æ from '../sounds/æ.ogg'
import ɐ from '../sounds/ɐ.ogg'
import ɑ from '../sounds/ɑ.ogg'
import ɒ from '../sounds/ɒ.ogg'
import b from '../sounds/b.ogg'
import ʙ from '../sounds/ʙ.ogg'
import ɓ from '../sounds/ɓ.ogg'
import c from '../sounds/c.ogg'
import ç from '../sounds/ç.ogg'
import d from '../sounds/d.ogg'
import ð from '../sounds/ð.ogg'
import dʒ from '../sounds/dʒ.ogg'
import ɖ from '../sounds/ɖ.oga'
import ɗ from '../sounds/ɗ.ogg'
import e from '../sounds/e.ogg'
import ə from '../sounds/ə.ogg'
import ɛ from '../sounds/ɛ.ogg'
import ɘ from '../sounds/ɘ.ogg'
import ɜ from '../sounds/ɜ.ogg'
import ɞ from '../sounds/ɞ.ogg'
import ɤ from '../sounds/ɤ.ogg'
import f from '../sounds/f.ogg'
import g from '../sounds/g.ogg'
import ɢ from '../sounds/ɢ.oga'
import ɠ from '../sounds/ɠ.ogg'
import ɣ from '../sounds/ɣ.ogg'
import h from '../sounds/h.ogg'
import ħ from '../sounds/ħ.ogg'
import ɦ from '../sounds/ɦ.ogg'
import i from '../sounds/i.ogg'
import ɪ from '../sounds/ɪ.ogg'
import ɨ from '../sounds/ɨ.ogg'
import j from '../sounds/j.ogg'
import ʝ from '../sounds/ʝ.ogg'
import ɟ from '../sounds/ɟ.ogg'
import k from '../sounds/k.ogg'
import kʼ from '../sounds/kʼ.ogg'
import l from '../sounds/l.ogg'
import ʟ from '../sounds/ʟ.ogg'
import ɬ from '../sounds/ɬ.ogg'
import ɭ from '../sounds/ɭ.ogg'
import ɮ from '../sounds/ɮ.ogg'
import ʎ from '../sounds/ʎ.ogg'
import m from '../sounds/m.ogg'
import ɱ from '../sounds/ɱ.ogg'
import n from '../sounds/n.ogg'
import ɴ from '../sounds/ɴ.ogg'
import ɲ from '../sounds/ɲ.ogg'
import ɳ from '../sounds/ɳ.ogg'
import ŋ from '../sounds/ŋ.ogg'
import o from '../sounds/o.ogg'
import ø from '../sounds/ø.ogg'
import œ from '../sounds/œ.ogg'
import ɶ from '../sounds/ɶ.ogg'
import ɔ from '../sounds/ɔ.ogg'
import ɵ from '../sounds/ɵ.ogg'
import p from '../sounds/p.ogg'
import pʼ from '../sounds/pʼ.ogg'
import ɸ from '../sounds/ɸ.ogg'
import q from '../sounds/q.ogg'
import r from '../sounds/r.ogg'
import ʀ from '../sounds/ʀ.ogg'
import ɹ from '../sounds/ɹ.ogg'
import ɻ from '../sounds/ɻ.ogg'
import ɽ from '../sounds/ɽ.ogg'
import ɾ from '../sounds/ɾ.ogg'
import ʁ from '../sounds/ʁ.ogg'
import s from '../sounds/s.ogg'
import ʂ from '../sounds/ʂ.ogg'
import ʃ from '../sounds/ʃ.ogg'
import t from '../sounds/t.ogg'
import tʃ from '../sounds/tʃ.ogg'
import tʼ from '../sounds/tʼ.ogg'
import ʈ from '../sounds/ʈ.oga'
import u from '../sounds/u.ogg'
import ʉ from '../sounds/ʉ.ogg'
import ɯ from '../sounds/ɯ.ogg'
import ɰ from '../sounds/ɰ.ogg'
import ʊ from '../sounds/ʊ.ogg'
import v from '../sounds/v.ogg'
import ʋ from '../sounds/ʋ.ogg'
import ʌ from '../sounds/ʌ.ogg'
import w from '../sounds/w.ogg'
import x from '../sounds/x.ogg'
import y from '../sounds/y.ogg'
import ʏ from '../sounds/ʏ.ogg'
import z from '../sounds/z.ogg'
import ʐ from '../sounds/ʐ.ogg'
import ʒ from '../sounds/ʒ.ogg'
import ʔ from '../sounds/ʔ.ogg'
import ʕ from '../sounds/ʕ.ogg'
import ǀ from '../sounds/ǀ.ogg'
import ǁ from '../sounds/ǁ.ogg'
import ǂ from '../sounds/ǂ.ogg'
import ǃ from '../sounds/ǃ.ogg'
import ʘ from '../sounds/ʘ.ogg'
import β from '../sounds/β.ogg'
import θ from '../sounds/θ.ogg'
import χ from '../sounds/χ.ogg'

const sound = {
'a' : a ,
'æ' : æ ,
'ɐ' : ɐ ,
'ɑ' : ɑ ,
'ɒ' : ɒ ,
'b' : b ,
'ʙ' : ʙ ,
'ɓ' : ɓ ,
'c' : c ,
'c' : ç,  
'd' : d ,
'ð' : ð ,
'dʒ' : dʒ,
'ɖ' : ɖ ,
'ɗ' : ɗ ,
'e' : e ,
'ə' : ə ,
'ɛ' : ɛ ,
'ɘ' : ɘ ,
'ɜ' : ɜ ,
'ɞ' : ɞ ,
'ɤ' : ɤ ,
'f' : f ,
'g' : g ,
'ɢ' : ɢ ,
'ɠ' : ɠ ,
'ɣ' : ɣ ,
'h' : h ,
'ħ' : ħ ,
'ɦ' : ɦ ,
'i' : i ,
'ɪ' : ɪ ,
'ɨ' : ɨ ,
'j' : j ,
'ʝ' : ʝ ,
'ɟ' : ɟ ,
'k' : k ,
'kʼ' : kʼ,
'l' : l ,
'ʟ' : ʟ ,
'ɬ' : ɬ ,
'ɭ' : ɭ ,
'ɮ' : ɮ ,
'ʎ' : ʎ ,
'm' : m ,
'ɱ' : ɱ ,
'n' : n ,
'ɴ' : ɴ ,
'ɲ' : ɲ ,
'ɳ' : ɳ ,
'ŋ' : ŋ ,
'o' : o ,
'ø' : ø ,
'œ' : œ ,
'ɶ' : ɶ ,
'ɔ' : ɔ ,
'ɵ' : ɵ ,
'p' : p ,
'pʼ' : pʼ,
'ɸ' : ɸ ,
'q' : q ,
'r' : r ,
'ʀ' : ʀ ,
'ɹ' : ɹ ,
'ɻ' : ɻ ,
'ɽ' : ɽ ,
'ɾ' : ɾ ,
'ʁ' : ʁ ,
's' : s ,
'ʂ' : ʂ ,
'ʃ' : ʃ ,
't' : t ,
'tʃ' : tʃ,
'tʼ' : tʼ,
'ʈ' : ʈ ,
'u' : u ,
'ʉ' : ʉ ,
'ɯ' : ɯ ,
'ɰ' : ɰ ,
'ʊ' : ʊ ,
'v' : v ,
'ʋ' : ʋ ,
'ʌ' : ʌ ,
'w' : w ,
'x' : x ,
'y' : y ,
'ʏ' : ʏ ,
'z' : z ,
'ʐ' : ʐ ,
'ʒ' : ʒ ,
'ʔ' : ʔ ,
'ʕ' : ʕ ,
'ǀ' : ǀ ,
'ǁ' : ǁ ,
'ǂ' : ǂ ,
'ǃ' : ǃ ,
'ʘ' : ʘ ,
'β' : β ,
'θ' : θ ,
'χ' : χ ,
}
export {sound}